baseURL = "https://billmainlandnelson.com/"
languageCode = "en-uk"
defaultContentLanguage  = "en"
isMultilingual          = false
title = "Bill Nelson"
theme = "bill2"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-135358161-1"

[params]
    author = "Bill Nelson"
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    #favicon             = "sam.ico"
    homepage            = "main"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = false                          # Allow links to the full size images
    footerText          = "© Bill Nelson 2019"

# Metadata
    #description         = "A new Hugo site."            # Max 160 characters show in search results
    #twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    #primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links



[[params.mainMenu]]
    link = "/about"
    text = "Bill Mainland Nelson"

[[params.mainMenu]]
    link = "/work"
    text = "Work"

[[params.mainMenu]]
    link = "/bicycles"
    text = "Bicycles"

