baseURL = "https://billmainlandnelson.com/"
languageCode = "en-uk"
defaultContentLanguage  = "en"
isMultilingual          = false
title = "Bill Mainland Nelson"
theme = "hugo-theme-sam"
pygmentsStyle           = "monokai"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
googleAnalytics         = "UA-135358161-1"
enableRobotsTXT         = true

[params]
    author = "Bill Nelson"
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "favicon.ico"
    homepage            = "Main"                        # What to call the home page link
    clickablePhotos     = false                          # Allow links to the full size images
    footerText          = "© 2019 Bill Mainland Nelson | [source code](https://github.com/billgeo/billmainlandnelson.com)"

# Metadata
    description         = "The official Bill Mainland Nelson. Poetry, writing, books, bicycles."
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "tn.png"                     # Image that shows on Twitter cards and OpenGraph links



[[params.mainMenu]]
    link = "/about"
    text = "Bill Mainland Nelson"

[[params.mainMenu]]
    link = "/work"
    text = "Writing"

[[params.mainMenu]]
    link = "/bicycles"
    text = "Bicycles"

